### ISSUE TITLE
mikrotik_routeros platform using incorrect command for config backup

### ISSUE THREAD

**Issue by gorbyhail** [netpicker/netpicker#4]
Hey, another issue but hopefully this one is simple :)

The mikrotik_routeros platform appears to be trying to use the command "show", which doesn't actually exist on routeros, for a config backup.

The "export" command is probably a better bet as this outputs the entire config with nothing hidden.

![image](https://github.com/netpicker/netpicker/assets/138606428/f1a4b0dd-f68a-482c-be80-90dfe558aefa)

**Comment by gorbyhail** [comment]
Just to add to this, I've attempted to change this myself using your guide here: [https://netpicker.io/knowledge-base/custom-config-backup-command-setup/](url)

![image](https://github.com/netpicker/netpicker/assets/138606428/3e9e1fc1-290e-4f50-aece-5de1d68b0df9)

Alas even after restarting Netpicker it is still trying to use `show` rather than `export`

**Comment by gorbyhail** [comment]
Used your guide here to change the config backup command: [https://netpicker.io/knowledge-base/custom-config-backup-command-setup/](url) and it is now working perfectly! Apologies for opening an issue before thoroughly checking your knowledgebase

**Comment by CopyBook-Maxim** [comment]
> Used your guide here to change the config backup command: [https://netpicker.io/knowledge-base/custom-config-backup-command-setup/](url) and it is now working perfectly! Apologies for opening an issue before thoroughly checking your knowledgebase

Hello

I too have encountered this problem. But as per the given link, this solution is not working for me.

I have added environment variables for agent container in docker-compose.yml. I also see in the inside of the container itself that this setting has appeared. 

But when collecting backups, I still get “bad command name show (line 1 column 1)”.

Could you please show me the configuration of your docker-compose.yml file for this case? 
 
Thanks!

Translated with DeepL.com (free version)

**Comment by ottocoster** [comment]
Which vendor and which config backup command are you using?

The `{vendor}` part in the `SHENV_SHOW_RUN_{vendor}` environment variable should match with the platform of the device in Netpicker.

**Comment by CopyBook-Maxim** [comment]
> Which vendor and which config backup command are you using?
> 
> The `{vendor}` part in the `SHENV_SHOW_RUN_{vendor}` environment variable should match with the platform of the device in Netpicker.



```
  agent:
    hostname: agent
    image: netpicker/agent:latest
    container_name: agent
    labels:
      service.netpicker.io: agent
    environment:
      CLI_PROXY_ADDR: '0.0.0.0'
      SHENV_SHOW_RUN_nokia_srl: 'info'
      SHENV_PRIVILEGED_PLATFORMS: 'privileged_platform'
      SHENV_SHOW_RUN_mikrotik_routeros: 'export'
```


Vendor - Mikrotik, platform - router.
I add env match with the platform of the device in Netpicker
